apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry-creds-handler.fullname" . }}
  labels:
    {{- include "registry-creds-handler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "registry-creds-handler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "registry-creds-handler.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    serviceAccountName: { { include "registry-creds-handler.serviceAccountName" . } }
      containers:
        - name: {{ template "registry-creds-handler.name" . }}-{{ .Values.name }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}
          args:
          {{- with .Values.registry }}
            - --secret-name={{ .secretName }}
            - --registry-kind={{ .kind }}
            {{- if .namespace }}
            - --namespace={{ .namespace }}
            {{- end }}
            {{- if .creds }}
            - --creds={{ .creds }}
            {{- end }}
            {{- if .registryUri }}
            - --registry-uri={{ .registryUri }}
            {{- end }}
          {{- end }}
          {{- range $key, $value := .Values.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
    {{- end }}
