{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "registry-creds-handler.fullname" . }}
  labels:
{{ include "registry-creds-handler.labels" . | nindent 4 }}
rules:
- apiGroups:      ['']
  resources:      ['secrets']
  verbs:          ['*']
{{- end }}
