{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "registry-creds-handler.fullname" . }}
  labels:
{{ include "registry-creds-handler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "registry-creds-handler.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "registry-creds-handler.serviceAccountName" . }}
{{- end -}}
