{{- if .Values.serviceAccounts.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "registry-creds-handler.serviceAccountName" . }}
  labels:
{{ include "registry-creds-handler.labels" . | nindent 4 }}
{{- end -}}
