{{- if .Values.minioPersistencyStandalone.pv.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    {{- include "mlrun-kit.minio.labels" . | nindent 4 }}
spec:
  storageClassName: "minio-host-path"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end -}}
