nameOverride:
fullnameOverride:

name: registry-creds-handler

# provide to allow application to create and refresh a docker registry auth secret
#registry:
#  secretName: example-secret-name
#  kind: ecr
#  namespace: default
#  creds: ""
#  registryUri: example.ecr.us-east-1.amazonaws.com/my-repo-name

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
## This can be useful for auth tokens, etc
envFromSecret: ""

extraArgs: {}

replicaCount: 1

image:
  repository: gcr.io/iguazio/registry-creds-handler
  tag: unstable
  pullPolicy: IfNotPresent
  pullSecrets: []

resources: {}
 # limits:
 #   cpu: 100m
 #   memory: 128Mi
 # requests:
 #   cpu: 100m
 #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""
