# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: spark-master
  Image: "iguaziodocker/spark"
  ImageTag: "2.1.2"
  ImagePullPolicy: "IfNotPresent"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "9096Mi"
  ServicePort: 7077
  ContainerPort: 7077
  RunAsUser: "iguazio"

WebUi:
  Name: spark-webui
  ServicePort: 8080
  ContainerPort: 8080
  NameSpace: "iguazio"
  NodePort: 32750

Worker:
  Name: spark-worker
  Image: "iguaziodocker/spark"
  ImageTag: "2.1.2"
  ImagePullPolicy: "IfNotPresent"
  Replicas: 1
  Component: "spark-worker"
  Cpu: "100m"
  Memory: "4096Mi"
  ContainerPort: 8081
  RunAsUser: "iguazio"

Zeppelin:
  Name: zeppelin
  Image: "iguaziodocker/zeppelin"
  ImageTag: "2.1.2"
  ImagePullPolicy: "IfNotPresent"
  Replicas: 1
  Component: "zeppelin"
  Cpu: "100m"
  ServicePort: 8080
  ContainerPort: 8080
  NodePort: 30280

V3IO:
  DaemonLookupServiceName: "registry"
  DaemonLookupServicePort: 8080
  DaemonLookupServicePath: "registry/daemon"
