{{- if .Values.jupyterPersistencyStandalone.pvc.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-pv
  labels:
    {{- include "mlrun-kit.jupyter.labels" . | nindent 4 }}
spec:
  storageClassName: "jupyter-host-path"
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/{{ template "mlrun-kit.fullname" . }}-jupyter
{{- end -}}
