{{- if .Values.jupyterPersistencyStandalone.pv.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  labels:
    {{- include "mlrun-kit.jupyter.labels" . | nindent 4 }}  
spec:
  storageClassName: "jupyter-host-path"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end -}}
